import Head from "next/head";
import Header from "../src/components/UI/Header";

export default function Home() {
    return (
        <>
            <Head>
                <title>Will Front-end Developer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
        </>
    );
}
